# Generated by Django 4.2.7 on 2025-11-04 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('habit_id', models.AutoField(primary_key=True, serialize=False)),
                ('habit_name', models.CharField(max_length=200)),
                ('habit_type', models.CharField(choices=[('READING', 'Reading'), ('COOKING', 'Cooking'), ('DRAWING', 'Drawing'), ('JOURNALING', 'Journaling'), ('OTHER', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habits',
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('habit_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('reminder_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habits.habit')),
            ],
            options={
                'db_table': 'habit_logs',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('pages_read', models.IntegerField()),
                ('habit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_details', to='habits.habit')),
            ],
            options={
                'db_table': 'reading_habits',
            },
        ),
        migrations.CreateModel(
            name='Journaling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('done', models.BooleanField(default=False)),
                ('habit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journaling_details', to='habits.habit')),
            ],
            options={
                'db_table': 'journaling_habits',
            },
        ),
        migrations.CreateModel(
            name='HabitLogNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('habit_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='habits.habitlog')),
            ],
            options={
                'verbose_name_plural': 'Habit Log Notes',
                'db_table': 'habit_log_notes',
            },
        ),
        migrations.CreateModel(
            name='HabitLogFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily', models.BooleanField(default=False)),
                ('weekly', models.BooleanField(default=False)),
                ('habit_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frequency', to='habits.habitlog')),
            ],
            options={
                'verbose_name_plural': 'Habit Log Frequencies',
                'db_table': 'habit_log_frequencies',
            },
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('inspiration', models.CharField(max_length=200)),
                ('habit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_details', to='habits.habit')),
            ],
            options={
                'db_table': 'drawing_habits',
            },
        ),
        migrations.CreateModel(
            name='Cooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('habit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cooking_details', to='habits.habit')),
            ],
            options={
                'db_table': 'cooking_habits',
            },
        ),
    ]
