# Generated by Django 4.2.7 on 2025-11-04 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('health_metric_id', models.AutoField(primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=200)),
                ('metric_description', models.TextField()),
                ('metric_value', models.FloatField()),
                ('metric_unit', models.CharField(max_length=50)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'health_metrics',
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('health_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('health_record_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_records',
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_value', models.FloatField(help_text='kg')),
                ('health_metric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weight', to='health_records.healthmetric')),
            ],
            options={
                'db_table': 'weight_metrics',
            },
        ),
        migrations.CreateModel(
            name='TeacherHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_record', to='health_records.healthrecord')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='users.teacher')),
            ],
            options={
                'db_table': 'teacher_health_records',
            },
        ),
        migrations.CreateModel(
            name='SugarLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugar_level_value', models.FloatField(help_text='mg/dL')),
                ('health_metric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sugar_level', to='health_records.healthmetric')),
            ],
            options={
                'db_table': 'sugar_level_metrics',
            },
        ),
        migrations.CreateModel(
            name='StudentHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_record', to='health_records.healthrecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='users.student')),
            ],
            options={
                'db_table': 'student_health_records',
            },
        ),
        migrations.CreateModel(
            name='Oxygen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oxygen_value', models.FloatField(help_text='SpO2 %')),
                ('health_metric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oxygen', to='health_records.healthmetric')),
            ],
            options={
                'db_table': 'oxygen_metrics',
            },
        ),
        migrations.CreateModel(
            name='Height',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_value', models.FloatField(help_text='cm')),
                ('health_metric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='height', to='health_records.healthmetric')),
            ],
            options={
                'db_table': 'height_metrics',
            },
        ),
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate_value', models.FloatField(help_text='BPM')),
                ('health_metric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='heart_rate', to='health_records.healthmetric')),
            ],
            options={
                'db_table': 'heart_rate_metrics',
            },
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='health_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='health_records.healthrecord'),
        ),
        migrations.CreateModel(
            name='Cholesterol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cholesterol_value', models.FloatField(help_text='mg/dL')),
                ('health_metric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cholesterol', to='health_records.healthmetric')),
            ],
            options={
                'db_table': 'cholesterol_metrics',
            },
        ),
    ]
