# Generated by Django 4.2.7 on 2025-11-05 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthmetric',
            name='health_record',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='health_metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='health_records.healthmetric'),
        ),
    ]
