# Generated by Django 4.2.7 on 2025-11-05 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0002_reverse_health_metric_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthmetric',
            name='metric_value',
        ),
    ]
