# Generated by Django 4.2.7 on 2025-11-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0003_remove_metric_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='value',
            field=models.FloatField(blank=True, help_text='Valeur du metric', null=True),
        ),
    ]
