# Generated by Django 4.2.7 on 2025-11-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0004_add_value_to_health_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='health_record_name',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='start_date',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='date',
            field=models.DateTimeField(blank=True, help_text='Date du record', null=True),
        ),
    ]
