# Generated by Django 4.2.7 on 2025-11-05 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0006_restore_start_end_date_and_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='health_record_name',
        ),
    ]
