# Generated by Django 4.2.7 on 2025-11-05 23:00

from django.db import migrations
from django.utils import timezone


def add_default_health_metrics(apps, schema_editor):
    """Add default health metrics from ontology"""
    HealthMetric = apps.get_model('health_records', 'HealthMetric')
    
    # Default health metrics based on ontology subclasses
    default_metrics = [
        {
            'metric_name': 'Heart Rate',
            'metric_description': 'Fréquence cardiaque (battements par minute)',
            'metric_unit': 'BPM',
        },
        {
            'metric_name': 'Cholesterol',
            'metric_description': 'Niveau de cholestérol dans le sang',
            'metric_unit': 'mg/dL',
        },
        {
            'metric_name': 'Sugar Level',
            'metric_description': 'Niveau de sucre dans le sang (glycémie)',
            'metric_unit': 'mg/dL',
        },
        {
            'metric_name': 'Oxygen Saturation',
            'metric_description': 'Saturation en oxygène (SpO2)',
            'metric_unit': '%',
        },
        {
            'metric_name': 'Height',
            'metric_description': 'Taille',
            'metric_unit': 'cm',
        },
        {
            'metric_name': 'Weight',
            'metric_description': 'Poids',
            'metric_unit': 'kg',
        },
    ]
    
    for metric_data in default_metrics:
        HealthMetric.objects.get_or_create(
            metric_name=metric_data['metric_name'],
            defaults={
                'metric_description': metric_data['metric_description'],
                'metric_unit': metric_data['metric_unit'],
                'recorded_at': timezone.now(),
            }
        )


def remove_default_health_metrics(apps, schema_editor):
    """Remove default health metrics (reverse migration)"""
    HealthMetric = apps.get_model('health_records', 'HealthMetric')
    
    metric_names = [
        'Heart Rate',
        'Cholesterol',
        'Sugar Level',
        'Oxygen Saturation',
        'Height',
        'Weight',
    ]
    
    HealthMetric.objects.filter(metric_name__in=metric_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0007_remove_health_record_name'),
    ]

    operations = [
        migrations.RunPython(add_default_health_metrics, remove_default_health_metrics),
    ]
