# Generated by Django 4.2.7 on 2025-11-04 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defi',
            fields=[
                ('defi_id', models.AutoField(primary_key=True, serialize=False)),
                ('defi_name', models.CharField(max_length=200)),
                ('defi_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Défi',
                'verbose_name_plural': 'Défis',
                'db_table': 'defis',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('participation_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('defi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='defis.defi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'participations',
            },
        ),
        migrations.CreateModel(
            name='ParticipationRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_value', models.IntegerField()),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='range', to='defis.participation')),
            ],
            options={
                'db_table': 'participation_ranges',
            },
        ),
        migrations.CreateModel(
            name='ParticipationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_value', models.IntegerField(help_text='Progress percentage (0-100)')),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='defis.participation')),
            ],
            options={
                'verbose_name_plural': 'Participation Progress',
                'db_table': 'participation_progress',
            },
        ),
        migrations.CreateModel(
            name='ParticipationNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_count', models.IntegerField()),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='number', to='defis.participation')),
            ],
            options={
                'db_table': 'participation_numbers',
            },
        ),
        migrations.CreateModel(
            name='DefiStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('in_progress', models.BooleanField(default=False)),
                ('defi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='defis.defi')),
            ],
            options={
                'verbose_name': 'Défi Status',
                'verbose_name_plural': 'Défi Statuses',
                'db_table': 'defi_status',
            },
        ),
        migrations.CreateModel(
            name='DefiObjectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('defi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='defis.defi')),
            ],
            options={
                'verbose_name': 'Défi Objectif',
                'db_table': 'defi_objectives',
            },
        ),
        migrations.CreateModel(
            name='DefiBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.BooleanField(default=False)),
                ('silver', models.BooleanField(default=False)),
                ('bronze', models.BooleanField(default=False)),
                ('defi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='badge', to='defis.defi')),
            ],
            options={
                'verbose_name': 'Défi Badge',
                'db_table': 'defi_badges',
            },
        ),
    ]
