# Generated by Django 4.2.7 on 2025-11-04 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('food_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_item_name', models.CharField(max_length=200)),
                ('food_item_description', models.TextField()),
                ('food_type', models.CharField(choices=[('PROTEIN', 'Protein'), ('CARBS', 'Carbohydrates'), ('FATS', 'Fats'), ('VEGETABLES', 'Vegetables'), ('FRUITS', 'Fruits')], max_length=20)),
            ],
            options={
                'db_table': 'food_items',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False)),
                ('meal_name', models.CharField(max_length=200)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACK', 'Snack')], max_length=20)),
                ('total_calories', models.IntegerField()),
                ('meal_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meals',
            },
        ),
        migrations.CreateModel(
            name='Sugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugar_value', models.IntegerField(help_text='grams')),
                ('food_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sugar', to='meals.fooditem')),
            ],
            options={
                'db_table': 'sugar',
            },
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snack_score', models.IntegerField(help_text='Nutritional score (1-100)')),
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snack_details', to='meals.meal')),
            ],
            options={
                'db_table': 'snack_meals',
            },
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_value', models.IntegerField(help_text='grams')),
                ('food_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='protein', to='meals.fooditem')),
            ],
            options={
                'db_table': 'protein',
            },
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch_score', models.IntegerField(help_text='Nutritional score (1-100)')),
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_details', to='meals.meal')),
            ],
            options={
                'verbose_name_plural': 'Lunches',
                'db_table': 'lunch_meals',
            },
        ),
        migrations.AddField(
            model_name='fooditem',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='meals.meal'),
        ),
        migrations.CreateModel(
            name='Fiber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiber_value', models.IntegerField(help_text='grams')),
                ('food_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiber', to='meals.fooditem')),
            ],
            options={
                'db_table': 'fiber',
            },
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinner_score', models.IntegerField(help_text='Nutritional score (1-100)')),
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dinner_details', to='meals.meal')),
            ],
            options={
                'db_table': 'dinner_meals',
            },
        ),
        migrations.CreateModel(
            name='Carbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbs_value', models.IntegerField(help_text='grams')),
                ('food_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carbs', to='meals.fooditem')),
            ],
            options={
                'verbose_name_plural': 'Carbs',
                'db_table': 'carbs',
            },
        ),
        migrations.CreateModel(
            name='Calories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories_value', models.IntegerField()),
                ('food_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calories', to='meals.fooditem')),
            ],
            options={
                'verbose_name_plural': 'Calories',
                'db_table': 'calories',
            },
        ),
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_score', models.IntegerField(help_text='Nutritional score (1-100)')),
                ('meal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='breakfast_details', to='meals.meal')),
            ],
            options={
                'db_table': 'breakfast_meals',
            },
        ),
    ]
