# Generated by Django 4.2.7 on 2025-11-04 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=200)),
                ('activity_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'db_table': 'activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('activity_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('intensity', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='activities.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
            },
        ),
        migrations.CreateModel(
            name='Natation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(help_text='Distance in meters')),
                ('style', models.CharField(choices=[('FREESTYLE', 'Freestyle'), ('BACKSTROKE', 'Backstroke'), ('BREASTSTROKE', 'Breaststroke'), ('BUTTERFLY', 'Butterfly'), ('PAPILLON', 'Papillon')], max_length=20)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='natation_details', to='activities.activity')),
            ],
            options={
                'db_table': 'natation_activities',
            },
        ),
        migrations.CreateModel(
            name='Musculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField()),
                ('repetitions', models.IntegerField()),
                ('weight', models.IntegerField(help_text='Weight in kg')),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='musculation_details', to='activities.activity')),
            ],
            options={
                'db_table': 'musculation_activities',
            },
        ),
        migrations.CreateModel(
            name='MediumIntensityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_time', models.IntegerField(help_text='Active time in minutes')),
                ('breaks_taken', models.IntegerField()),
                ('activity_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medium_intensity', to='activities.activitylog')),
            ],
            options={
                'db_table': 'medium_intensity_logs',
            },
        ),
        migrations.CreateModel(
            name='LowIntensityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breathing_rate', models.CharField(max_length=50)),
                ('comfort_level', models.IntegerField(help_text='Comfort level (1-10)')),
                ('activity_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='low_intensity', to='activities.activitylog')),
            ],
            options={
                'db_table': 'low_intensity_logs',
            },
        ),
        migrations.CreateModel(
            name='HighIntensityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lactic_acid_level', models.FloatField()),
                ('injury_risk', models.CharField(max_length=50)),
                ('activity_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='high_intensity', to='activities.activitylog')),
            ],
            options={
                'db_table': 'high_intensity_logs',
            },
        ),
        migrations.CreateModel(
            name='Cardio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories_burned', models.FloatField()),
                ('heart_rate', models.IntegerField(help_text='Heart rate in BPM')),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cardio_details', to='activities.activity')),
            ],
            options={
                'db_table': 'cardio_activities',
            },
        ),
    ]
